### ISSUE TITLE
Is support for Raspberry Pi possible?

### ISSUE THREAD

**Issue by DemonKingFukai** [fsphil/hacktv#102]
RPItx, PiFM, and various other softwares and hardwares use pin 7 on a raspberry pi to transmit various signals. Is it possible to utilize this for transmission using HackTV? There is support for FL2k so I thought Raspberry Pi would be supported as well.

**Comment by fsphil** [comment]
Technically yes, but only the two narrowband TV modes `30-am` and `nbtv-am` would work. The maximum bandwidth of 250kHz just isn't enough to fit a standard 525/625-line TV signal - it would need to be at least 25 times wider.

**Comment by 03stevensmi** [comment]
Wouldn't something like one of those rpi tx hat work? There are a few that can boost the rpi to a much wider band and frequency.

**Comment by fsphil** [comment]
Have you got a link to one?

**Comment by 03stevensmi** [comment]
> Have you got a link to one?

Sure,
Here is one
https://github.com/cariboulabs/cariboulite

**Comment by fsphil** [comment]
Its analogue bandwidth is 2.5 MHz, better but still too narrow for an NTSC/PAL TV mode.
You may be able to get monochrome video from it but it wouldn't look all that good.
