### ISSUE TITLE
TV Guides/Listings/Channel Information

### ISSUE THREAD

**Issue by thatguycy** [fsphil/hacktv#103]
Is there any way to transmit Channel Information or Guides over Analogue using HackRF? I didn't see any other issues about this and I was curious so I made one.

**Comment by fsphil** [comment]
Do you mean Guide Plus (https://en.wikipedia.org/wiki/Guide_Plus)? Or something else?

**Comment by thatguycy** [comment]
Like the TV Guides found actually on the TV

![image](https://github.com/fsphil/hacktv/assets/33783071/ee199c81-9a93-4324-8f8f-d30feab934e6)
![image](https://github.com/fsphil/hacktv/assets/33783071/33d26774-7998-4bea-9af9-218d30abfd82)

**Comment by fsphil** [comment]
Those are all DVB digital TV services. The only analogue TV equivalent I ever saw for that was simply the TV guide pages on teletext, which you can definitely do with hacktv - you just have to write the pages.

**Comment by thatguycy** [comment]
I don't know anything about teletext, but thank you so much! I'll research it!

**Comment by fsphil** [comment]
No worries. There used to be dedicated EPG-style services like Guide Plus above in the US and other countries for analogue TV, but I don't have any real technical info about how they worked.
