### ISSUE TITLE
Bug in Syster-Encoder?

### ISSUE THREAD

**Issue by neo7530** [fsphil/hacktv#17]
Hi,
is there any bug in the syster encoder? In the decoded picture i have many stripes / Lines jumping arround on wrong positions... Have tested per live-view in MeuhMeuh-TV aswell the decoded baseband-file per offline descrambler (cryptimage). There all the same stripes in the top of the picture. I have tested my own encrypded videos, they didn't have any stripes in view.

Regards, Marco.

**Comment by Zcooger** [comment]
There is no bug. Some capture cards send the picture with subtle line shift, it means 2 lines may be added on the bottom so you have to adjust the shift in MMTV settings.

**Comment by neo7530** [comment]
but when i decode the baseband manually, then no capture-card is involved, so it have to be clean i think....

**Comment by Zcooger** [comment]
Is your baseband file made in 626 lines or 625?

**Comment by neo7530** [comment]
625

**Comment by neo7530** [comment]
https://gtrx1.selfip.net/stripes.jpg look @ this

**Comment by Zcooger** [comment]
Send them both maybe

**Comment by neo7530** [comment]
it tooks a moment, have to boot my linux-pc ...

**Comment by neo7530** [comment]
https://gtrx1.selfip.net/clear.png it is a clear image

**Comment by Zcooger** [comment]
While trying to decrypt in MMTV you can try to adjust bad picture shift caused by capture card itself or it's driver before it goes to the decoder - try all possible values closest to 0:
![obraz](https://user-images.githubusercontent.com/42012614/51080051-b827ba80-16d4-11e9-9b1b-d5ae4592cafe.png)
Cryptimage baseband decoding is not perfect too.

**Comment by neo7530** [comment]
https://gtrx1.selfip.net/sys0000.png baseband decoded syster-frame

**Comment by neo7530** [comment]
Okay, will give it a try tomorrow... Thank you anyway.

**Comment by neo7530** [comment]
aahhhrrrgghhhhssss... -2 was the magic number.... now all the stripes are gone...
