### ISSUE TITLE
Building for Windows

### ISSUE THREAD

**Issue by neo7530** [fsphil/hacktv#18]
...and compile it for Windows... I run on errors while compiling it (FFMPEG, LIBHACKRF)

Thank you.

**Comment by Zcooger** [comment]
+1

**Comment by neo7530** [comment]
don't want to boot 2 computers to play with it, so it would be nice, if i had it for windows...

**Comment by Zcooger** [comment]
Getting it to work on second partition or VM takes some time along with transferring heavy .raw files generated by HackRF from guest OS to host OS.

**Comment by SAUCYSOUP76** [comment]
@neo7530 have you considered dual booting? I'm using this under linux and it works perfectly.
@Zcooger well it'll be quicker than waiting for the dev to compile it for windows as for me the compiliation time was roughly under a few seconds.

**Comment by fsphil** [comment]
Can someone test this build please: https://www.sanslogic.co.uk/hacktv/hacktv-20190131-x86_64.zip

**Comment by neo7530** [comment]
jiippyyy... works like a charm. have to reset the hackrf after transmitting, but it works :)

**Comment by SAUCYSOUP76** [comment]
> well it'll be quicker than waiting for the dev to compile it for windows

haha disregard that comment :)

**Comment by Zcooger** [comment]
For my needs it works fine, thanks.

**Comment by neo7530** [comment]
Perfect. @Fsphil, can you post the steps to compile it for Windows, please? Many thanks.

**Comment by SAUCYSOUP76** [comment]
@neo7530 i take it compiling c is not the same on windows as it is on linux?
for me it's cd hacktv and then make and make install.

**Comment by fsphil** [comment]
I've added a script which will attempt to build hacktv for Windows x86_64:

`$ ./build_win64.sh`

The required packages for each distro will vary, but on Fedora I believe you just need: `git make libtool mingw64-gcc mingw64-gcc-c++ mingw64-winpthreads-static mingw64-pkg-config`

**Comment by neo7530** [comment]
Something goes wrong with this version when i build it for Windows in fedora:
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lbz2
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lz
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -liconv
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lz

Do you have an idea?
Thank you.

**Comment by fsphil** [comment]
Which version of Fedora? It's working fine here on Fedora 29 (x86_64).

**Comment by neo7530** [comment]
same version... Fedora 29 
Are there some missing libs in my system?

**Comment by fsphil** [comment]
Have you made any changes?

**Comment by neo7530** [comment]
Nope... the old builds still compiling right...

**Comment by fsphil** [comment]
Can you show me the lines above the error, the context might help.

**Comment by neo7530** [comment]
+ HOST=x86_64-w64-mingw32
++ pwd
+ PREFIX=/home/marco/compile/hacktv/build_win64/install_root
+ export PKG_CONFIG_PATH=/home/marco/compile/hacktv/build_win64/install_root/lib/pkgconfig
+ PKG_CONFIG_PATH=/home/marco/compile/hacktv/build_win64/install_root/lib/pkgconfig
+ mkdir -p /home/marco/compile/hacktv/build_win64/install_root
+ cd build_win64
+ [[ ! -f /home/marco/compile/hacktv/build_win64/install_root/lib/libusb-1.0.a ]]
+ [[ ! -f /home/marco/compile/hacktv/build_win64/install_root/lib/libhackrf.a ]]
+ [[ ! -f /home/marco/compile/hacktv/build_win64/install_root/lib/libosmo-fl2k.a ]]
+ [[ ! -f /home/marco/compile/hacktv/build_win64/install_root/lib/libfdk-aac.a ]]
+ [[ ! -f /home/marco/compile/hacktv/build_win64/install_root/lib/libopus.a ]]
+ [[ ! -f /home/marco/compile/hacktv/build_win64/install_root/lib/libavformat.a ]]
+ cd ..
+ CROSS_HOST=x86_64-w64-mingw32-
+ make -j4 EXTRA_LDFLAGS=-static EXTRA_PKGS=libusb-1.0
x86_64-w64-mingw32-gcc -o hacktv hacktv.o common.o fir.o vbidata.o teletext.o wss.o video.o videocrypt.o syster.o nicam728.o test.o ffmpeg.o file.o hackrf.o fl2k.o -g -lm -pthread -static -L/home/marco/compile/hacktv/build_win64/install_root/lib -lavdevice -lpsapi -lole32 -lstrmiids -luuid -loleaut32 -lshlwapi -lgdi32 -lm -lvfw32 -lavfilter -lm -lpostproc -lm -lavformat -lm -lbz2 -lz -lsecur32 -lws2_32 -lavcodec -liconv -lm -lz -lfdk-aac -lopus -lole32 -luser32 -lswscale -lm -lswresample -lm -lavutil -lm -luser32 -lbcrypt -lhackrf -lusb-1.0 -losmo-fl2k -lusb-1.0 
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lbz2
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lz
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -liconv
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make: *** [Makefile:29: hacktv] Fehler 1

**Comment by fsphil** [comment]
Thanks. At first glance it looks like something has changed in ffmpeg. I'm rebuilding it from fresh here now, will see if the error appears.

**Comment by fsphil** [comment]
It's still building fine here. Can you try from a fresh directory? Run "make clean" and delete the build_win64 directory.

**Comment by neo7530** [comment]
still the same issue :(

**Comment by fsphil** [comment]
I've just tried on a fresh install of Fedora 30 and it worked fine. There must be something outside of your build directory that's causing ffmpeg to pull in the -lz and -lbz2 libraries. I'm not sure what it could be.

**Comment by neo7530** [comment]
Will test it later with a fresh install and report. Thank you.

**Comment by neo7530** [comment]
ackrf-2018.01.1/issue_template.md
+ rm -rf hackrf-2018.01.1/host/libhackrf/build
+ mkdir -p hackrf-2018.01.1/host/libhackrf/build
+ cd hackrf-2018.01.1/host/libhackrf/build
+ mingw64-cmake -DCMAKE_INSTALL_PREFIX=/root/compile/hacktv/build_win64/install_root -DCMAKE_INSTALL_LIBPREFIX=/root/compile/hacktv/build_win64/install_root/lib -DLIBUSB_INCLUDE_DIR=/root/compile/hacktv/build_win64/install_root/include/libusb-1.0 -DLIBUSB_LIBRARIES=/root/compile/hacktv/build_win64/install_root/lib/libusb-1.0.a
/usr/bin/mingw64-cmake: Zeile 84: fg: Keine Job Steuerung in dieser Shell.

No job control in this shell... what is this? Fedora 30 fresh install... :/

**Comment by neo7530** [comment]
found it... had to install cmake...
