### ISSUE TITLE
Scrambled baseband output is delayed due to empty buffer lines

### ISSUE THREAD

**Issue by Zcooger** [fsphil/hacktv#25]
This issue does not affect complex output at all - only file output where not every viewing application let the user to skip desired amount of data (header skip).
FTA:
![clear_0_rgb](https://user-images.githubusercontent.com/42012614/52588562-11eae400-2e3d-11e9-808b-1d050200ef23.png)
Datacom Videocrypt - added one buffer line:
![videocrypt_0_rgb](https://user-images.githubusercontent.com/42012614/52588634-35159380-2e3d-11e9-96aa-2f0d4bb5ab1a.png)
Nagravision Syster - added 344 buffer lines:
![syster_0_rgb](https://user-images.githubusercontent.com/42012614/52588603-262ee100-2e3d-11e9-8ac3-63716b9c512e.png)

**Comment by fsphil** [comment]
This is not a bug, hacktv's output is not intended for display like this. But it is handy to have the output aligned for testing, so I've applied a fix for it.

Your decoder software should be using the sync pulses to find the start of a frame rather than making assumptions.

**Comment by Zcooger** [comment]
Hello, I applied your fixes to HackTV but the first baseband frame is still the same.

**Comment by fsphil** [comment]
Looks fine here?
![00000001](https://user-images.githubusercontent.com/229057/52891257-cfe5d900-3181-11e9-949b-02b50ff494b3.png)

**Comment by Zcooger** [comment]
Yup.
