### ISSUE TITLE
WSS line in Videocrypt mode

### ISSUE THREAD

**Issue by neo7530** [fsphil/hacktv#30]
The wss-line is added after encryption, so it will be scrambled after decryption and won't detect by tv anymore. It should be added before scrambling.

**Comment by fsphil** [comment]
It is being applied before scrambling, and works on my TV. Are you seeing something different?

**Comment by neo7530** [comment]
After decryption the First videoline is jumping left and right... So wss data were unreadable... Will test it again, and will make a Screenshot.

**Comment by fsphil** [comment]
OK to close this one?

**Comment by neo7530** [comment]
Ya, close it, it is fine.
