### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by alexmyczko** [fsphil/hacktv#38]
Hi !

Awesome work on hacktv!

Can you make a "release" on github to ease the download for the non "github-aware" people interested on this work ?

would be great to get this solved for https://release.debian.org/bullseye/freeze_policy.html

Thanks !

**Comment by eried** [comment]
Better if it includes windows binaries :D

**Comment by fsphil** [comment]
I've added a version number based on the most recent commit date and hash.
It won't work outside of a git repo so I'm not sure if this helps or hinders package maintainers.
