### ISSUE TITLE
Macrovision

### ISSUE THREAD

**Issue by Zcooger** [fsphil/hacktv#44]
To satisfy meticulousness I enclose here samples with macrovision signal - just for the sake of completeness. I embed some samples:

* Digital MV Remake of Panasonic DVD Recorder in Pass-Thru TBC mode:
![TV2019091206031900](https://user-images.githubusercontent.com/42012614/64826631-92cfb100-d5c1-11e9-8391-440a9184f606.jpg)

* Original MV pulses on protected VHS tape:
![TV2019091206014800](https://user-images.githubusercontent.com/42012614/64825716-87c75180-d5be-11e9-8d0a-0384df7dc89d.jpg)

* Video:
[mv.7z.zip](https://github.com/fsphil/hacktv/files/3607729/mv.7z.zip)

**Comment by fsphil** [comment]
Good idea, this could be fun to try. I have a Disney tape somewhere, I'll see if I can get the amplitude of the white blocks from that. From what I've read they're higher than normal video white.

It would be nice to have a raw capture of the NTSC version too.

**Comment by Zcooger** [comment]
I found some nice docs here (german):
http://www.strohbeck.net/ing/projekte/videokonverter.html

**Comment by fsphil** [comment]
Also here: https://www.maxlinear.com/Files/Documents/TMC2491A.pdf

**Comment by fsphil** [comment]
I've pushed some code to try this out, use --acp to enable. I haven't tested it on a VHS recorder yet.

**Comment by fsphil** [comment]
OK I give it a go on a VHS recorder and it didn't have much effect :-) I guess it's not quite right.

**Comment by Zcooger** [comment]
It triggers ACP in my Panasonic DVD recorder just like on the first snapshot.

**Comment by Zcooger** [comment]
https://youtu.be/VLbc-2vTEb0

**Comment by fsphil** [comment]
I've pushed some code to vary the AGC pulse amplitude over time. Macrovision uses other tricks too but I think this is enough for now. Closing the ticket. Thanks for the suggestion!

**Comment by Zcooger** [comment]
Amplitute variation test: https://www.youtube.com/watch?v=yNjfuLDN1JQ

**Comment by fsphil** [comment]
Would you mind if I used this video on twitter?

**Comment by Zcooger** [comment]
Use it, use it! Especially the 50fps version.
