### ISSUE TITLE
--wss switch erases second half of picture information on line 23

### ISSUE THREAD

**Issue by Zcooger** [fsphil/hacktv#46]
The whole line contains only the tag.
Example showing this error:
![wss_blank](https://user-images.githubusercontent.com/42012614/64854572-36e74580-d61e-11e9-9cab-d477c7c671c3.png)
Example showing complete 23rd line:
![dvd_wss](https://user-images.githubusercontent.com/42012614/64855128-7eba9c80-d61f-11e9-9a1f-8f52b777292e.png)

**Comment by fsphil** [comment]
The WSS signal overlapped the video on the second half of line 23 so I just blanked it completely.
It's difficult to say if this is an error, the specification ([EN 300 294](https://www.etsi.org/deliver/etsi_en/300200_300299/300294/01.03.02_60/en_300294v010302p.pdf)) doesn't mention video at all. There is just this:

> For optimum decoder performance, it is recommended that this period is free from other signals.

**Comment by Zcooger** [comment]
Ok, I just base this ticket on my observations of my 3 DVD players and a DVB-T receiver output.

**Comment by fsphil** [comment]
Do they all use the same timing? Can you measure how many microseconds it is from the start of the line?

**Comment by Zcooger** [comment]
Sure. I will check it on every device I have.

**Comment by fsphil** [comment]
Ah wait, I think I found it. It should be 42.5μs
