### ISSUE TITLE
Vertical Interval Time Code (VITC)

### ISSUE THREAD

**Issue by Zcooger** [fsphil/hacktv#51]
This ticket is made to suggest adding vertical blanking time code (VITC).
Quick non-technical demonstration: https://www.youtube.com/watch?v=aU40YRBa6nk
I wondered how this feature would work but first simple idea I got is to place time information of media file played back at the current moment.
Such signal can "fake" any professional video cassette deck.

**Comment by fsphil** [comment]
Do you have or know of any devices that can make use of the feature?

**Comment by Zcooger** [comment]
I don't have any Betacam SP or any professional gear to test that with but I found such signal on this repair demo of Sony PVW-2800 P so there is one example:

![obraz](https://user-images.githubusercontent.com/42012614/67402067-8c106280-f59f-11e9-8c58-76384466d23e.png)

https://www.youtube.com/watch?v=HDQB1Ck_UjY

Besides this Cassette deck there were in use timecode inserters, extractors and counters. Some displays can use OSD to show it.
I found it also on my VHS tapes with live TV recordings where it slipped to the VBI during broadcast like here:

https://upload.wikimedia.org/wikipedia/de/3/34/Vitc-PAL.jpg
![obraz](https://user-images.githubusercontent.com/42012614/67403609-b5ca8900-f5a1-11e9-8337-703662132cbe.png)

Now I found software that reads TC out of digitized video frames: https://www.videotoolshed.com/old/vitc-reader/

**Comment by 03stevensmi** [comment]
@fsphil @Zcooger @captainjack64 I would like to add that this is something I actually need to be able to make use of my old videomatte vm1 video mixer. I unfortunately can't use havktv because old video equipment like mixers etc need tbc vertical locked signals otherwise it just messes destroys the composite signal when in use with many of these old devices. Could you please add this feature?

**Comment by fsphil** [comment]
I've pushed a VITC inserter, you can try it with `--vitc`. It should work with NTSC and PAL modes, but I have only been able ot test it with ffmpeg's `readvitc` filter. I'd appreciate some testing with real hardware if anyone has it.

**Comment by fsphil** [comment]
> otherwise it messed up destroys the composite signal when in use with many of these old devices

This may still be an issue - right now hacktv doesn't set the colour framing bit. You might need this set, it's at https://github.com/fsphil/hacktv/blob/master/vitc.c#L136

**Comment by fsphil** [comment]
One potential issue, the field flag seems to be in a different location for 25 fps modes vs. others. Right now it's fixed at the 25 fps position.

**Comment by 03stevensmi** [comment]
> One potential issue, the field flag seems to be in a different location for 25 fps modes vs. others. Right now it's fixed at the 25 fps position.

have you (or anyone here) got a compiled windows build i can test?
just set up eveerything and i am ready to give it a shot.

Thanks fsphil for all your work.
You have just saved my ass on this one let me tell ya ;)
once i get a hold of a windows build i will let you know if it works.
thank you!

03stevensmi

**Comment by fsphil** [comment]
No worries. I'll close the issue for the moment. If you or anyone else are able to test it, drop a note here!
