### ISSUE TITLE
No frequency above 4 294 967 295 hz 

### ISSUE THREAD

**Issue by neo7530** [fsphil/hacktv#55]
I have an issue on some machines that I can't get above 4 294 967 295 hz transmitting frequency. That's 0XFFFFFFFF => 32bit. On my Linux machine it works well above that frequency. e.g. 5.837Ghz... There must be some overflow in conversion.

**Comment by fsphil** [comment]
gcc version, 32/64-bit, OS version?

**Comment by neo7530** [comment]
gcc (Raspbian 8.3.0-6+rpi1) 8.3.0
64bit os

**Comment by fsphil** [comment]
I've pushed a small tweak to the frequency parsing, can you try it now?

**Comment by neo7530** [comment]
Now it works perfect :)
