### ISSUE TITLE
A hacktv help command tells that no HackRF has been found

### ISSUE THREAD

**Issue by Zcooger** [fsphil/hacktv#58]
![image](https://user-images.githubusercontent.com/42012614/75493531-f869fb00-59b1-11ea-845d-af4d17c08eae.png)

**Comment by Zcooger** [comment]
It happens while FL2K adapter is connected.

**Comment by Zcooger** [comment]
Same applies to `hacktv ?`

**Comment by fsphil** [comment]
`hacktv help` will try to play a file named "help". You need `hacktv --help`

**Comment by Zcooger** [comment]
Ok, I realized it after a while.
