### ISSUE TITLE
A successful PAL 525/60 test

### ISSUE THREAD

**Issue by Zcooger** [fsphil/hacktv#59]
Hello - I can confirm that this mode works fine:
![image](https://user-images.githubusercontent.com/42012614/75494856-14bb6700-59b5-11ea-9039-9d087eb5b0f5.png)
![image](https://user-images.githubusercontent.com/42012614/75494178-91e5dc80-59b3-11ea-8b6a-733d7a6c1d55.png)

**Comment by fsphil** [comment]
Ah great. Thanks!
