### ISSUE TITLE
Shouldn't the teletext lines be active all the time...

### ISSUE THREAD

**Issue by Zcooger** [fsphil/hacktv#61]
...regardless of available teletext page amount?
Small comparison:
![ds030](https://user-images.githubusercontent.com/42012614/75611345-a63feb80-5b11-11ea-8b09-cc5d0bef96b7.png)
![ds006](https://user-images.githubusercontent.com/42012614/75611371-da1b1100-5b11-11ea-8c90-09d7a74f4b42.png)

**Comment by fsphil** [comment]
Not necessarily. If you're just transmitting a single page, there will be blanks due to the 20ms rule:

> For compatibility with earlier decoders in the field, a page clearing interval of 20 ms should be maintained in the transmission between the header and any packets of a page that is intended to be interpreted by a Level 1 or 1.5 decoder. This time interval is required by many decoders for erasing the previous page from memory
