### ISSUE TITLE
Videocrypt image is interfering with teletext data

### ISSUE THREAD

**Issue by Zcooger** [fsphil/hacktv#62]
The command used for it:
`hacktv test -o txt_vc_wss.bin --teletext demo.tti -m pal -t uint16 --videocrypt free`
It appears mostly on second field.
![image](https://user-images.githubusercontent.com/42012614/75616029-642f9d80-5b43-11ea-9ac0-0ccc3cac5d1c.png)
Black dots with overflown values.

**Comment by fsphil** [comment]
Well spotted. Line 336 is being scrambled and output on line 335 in the VBI area causing the clash. I've pushed a fix for this, can you test it please.

**Comment by Zcooger** [comment]
Good:
![image](https://user-images.githubusercontent.com/42012614/75616574-837df900-5b4a-11ea-8ef5-56905dc8a5d9.png)
