### ISSUE TITLE
Add version number for hacktv

### ISSUE THREAD

**Issue by Potomac** [fsphil/hacktv#76]
Currently hacktv doesn't have version number (no cli option --version or -v), it would be interesting to have this feature, 

a scheme like :
major.minor[.build[.revision]] (example: 1.2.12.102)

**Comment by fsphil** [comment]
There is no version number, but I've played about with using a yyyymmdd-commit style version:

```
$ ./hacktv --version
hacktv 20210116-751e496
```

Though I'm not completely happy with it.

**Comment by alexmyczko** [comment]
this is related to https://github.com/fsphil/hacktv/issues/38

**Comment by fsphil** [comment]
In the absence of any better ideas, I've gone with the hacktv date-sommit format:
```
$ ./hacktv --version
hacktv 20240721-e3cfc6f
```

I may change how this works in future but the version format will always at least be hacktv yyyymmdd
