### ISSUE TITLE
Error when install /  soapysdr.c:135:5 Error  too many arguments

### ISSUE THREAD

**Issue by Klammraute** [fsphil/hacktv#77]
Hi,
i when i try to install hacktv i get the following error when i try to "make" 

root@listen:/home/listen# cd hacktv-master
root@listen:/home/listen/hacktv-master# make
gcc -g -Wall -pthread -O3  -DHAVE_SOAPYSDR -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include/ -I/usr/include/libusb-1.0 -c soapysdr.c -o soapysdr.o
soapysdr.c: In function ‘rf_soapysdr_open’:
soapysdr.c:135:39: warning: passing argument 2 of ‘SoapySDRDevice_setupStream’ makes integer from pointer without a cast [-Wint-conversion]
  135 |  if(SoapySDRDevice_setupStream(rf->d, &rf->s, SOAPY_SDR_TX, SOAPY_SDR_CS16, NULL, 0, NULL) != 0)
      |                                       ^~~~~~
      |                                       |
      |                                       SoapySDRStream ** {aka struct SoapySDRStream **}
In file included from soapysdr.c:20:
/usr/local/include/SoapySDR/Device.h:306:31: note: expected ‘int’ but argument is of type ‘SoapySDRStream **’ {aka ‘struct SoapySDRStream **’}
  306 | SOAPY_SDR_API SoapySDRStream *SoapySDRDevice_setupStream(SoapySDRDevice *device,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
soapysdr.c:135:61: warning: passing argument 4 of ‘SoapySDRDevice_setupStream’ from incompatible pointer type [-Wincompatible-pointer-types]
  135 |  if(SoapySDRDevice_setupStream(rf->d, &rf->s, SOAPY_SDR_TX, SOAPY_SDR_CS16, NULL, 0, NULL) != 0)
      |                                                             ^~~~~~~~~~~~~~
      |                                                             |
      |                                                             char *
In file included from soapysdr.c:20:
/usr/local/include/SoapySDR/Device.h:306:31: note: expected ‘const size_t *’ {aka ‘const long unsigned int *’} but argument is of type ‘char *’
  306 | SOAPY_SDR_API SoapySDRStream *SoapySDRDevice_setupStream(SoapySDRDevice *device,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
soapysdr.c:135:77: warning: passing argument 5 of ‘SoapySDRDevice_setupStream’ makes integer from pointer without a cast [-Wint-conversion]
  135 |  if(SoapySDRDevice_setupStream(rf->d, &rf->s, SOAPY_SDR_TX, SOAPY_SDR_CS16, NULL, 0, NULL) != 0)
      |                                                                             ^~~~
      |                                                                             |
      |                                                                             void *
In file included from soapysdr.c:20:
/usr/local/include/SoapySDR/Device.h:306:31: note: expected ‘size_t’ {aka ‘const long unsigned int’} but argument is of type ‘void *’
  306 | SOAPY_SDR_API SoapySDRStream *SoapySDRDevice_setupStream(SoapySDRDevice *device,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
**soapysdr.c:135:5: error: too many arguments to function ‘SoapySDRDevice_setupStream’
  135 |  if(SoapySDRDevice_setupStream(rf->d, &rf->s, SOAPY_SDR_TX, SOAPY_SDR_CS16, NULL, 0, NULL) != 0)**
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from soapysdr.c:20:
/usr/local/include/SoapySDR/Device.h:306:31: note: declared here
  306 | SOAPY_SDR_API SoapySDRStream *SoapySDRDevice_setupStream(SoapySDRDevice *device,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:32: soapysdr.o] Fehler 1
root@listen:/home/listen/hacktv-master# sudo make install
cp -f hacktv /usr/local/bin/
cp: Aufruf von stat für 'hacktv' nicht möglich: Datei oder Verzeichnis nicht gefunden
make: *** [Makefile:36: install] Fehler 1

**Comment by fsphil** [comment]
This should be fixed now.
