### ISSUE TITLE
a2stereo option not automatically disables nicam

### ISSUE THREAD

**Issue by itewreed** [fsphil/hacktv#79]
To make a2stereo work, it is also necessary to use the nonicam parameter on the commandline. E.g --a2stereo --nonicam
Not doing so seems to have both, a2stereo and nicam, active. In this case a receiving device cannot detect a2stereo and the transmission still seems mono.
Test was done on two VCRs with stereo reception capability.

I suppose, that by using a2stereo option, the nicam should automatically be deactivated.

**Comment by fsphil** [comment]
Agreed. `--a2stereo` will disable NICAM now.

**Comment by itewreed** [comment]
As with the latest pull of August 13th, the issue still is present. To make a2stereo work I still need to use the --nonicam parameter.

**Comment by fsphil** [comment]
It seems fine here. Can you share the command line you are using?

**Comment by itewreed** [comment]
Found the mistake. I forgot to run the make command after pulling the update. Sorry for the inconvenience.
