### ISSUE TITLE
Livestreaming

### ISSUE THREAD

**Issue by Extrathestral64** [fsphil/hacktv#8]
I'm not sure how I would go about buffering the video in a livestream

**Comment by nat2001** [comment]
What are you streaming?

**Comment by fsphil** [comment]
The ffmpeg code is in dire need of some updates, including better handling of network input streams. I'm planning on splitting the input and decoder parts into their own thread, which should hopefully improve overall performance and reliability when reading over a network.

**Comment by Extrathestral64** [comment]
I would be transmitting a local video saved on the hard drive, preferably in mp4 format, although it's not a requirement

**Comment by Extrathestral64** [comment]
I would like to stream my screen, or more preferably a specific window on my screen

**Comment by MahmoudThePeltist** [comment]
Follow up question, is it possible to stream from a webcam using hacktv?

**Comment by fsphil** [comment]
Not currently. There's no way to pass a format to the ffmpeg library (the -f flag in ```ffmpeg```). This is also needed for screen capture.

**Comment by Extrathestral64** [comment]
Is there a way to pipe video in currently?

**Comment by fsphil** [comment]
Specify /dev/stdin as the input.

**Comment by fsphil** [comment]
The latest commit 87c0c8b2d9352352afaa559e0bb84062ffe72f60 should help with playing live streams. Closing this issue.
