### ISSUE TITLE
A Recent build of hacktv for Windows x64?

### ISSUE THREAD

**Issue by 03stevensmi** [fsphil/hacktv#90]
Hi Guys,
Can someone here share an updated recent windows x64 exe build of hacktv please?

I can only find the 2021 version and need a more updated version 
ether from CaptainJack's hacktv fork,
or from fsphil.

Thank You.

**Comment by alexjcirrushq** [comment]
The latest CJ fork's binary is always here https://filmnet.plus/hacktv/hacktv.zip

**Comment by 03stevensmi** [comment]
thanks mate ;)
