### ISSUE TITLE
where does the TV logos come from?

### ISSUE THREAD

**Issue by 03stevensmi** [fsphil/hacktv#91]
Can anyone here tell me where the tv channel logos url came from and how i can find them?
I am doing some experiments with hacktv and virtualdub and need the png logo's for virtualdub.

**Comment by captainjack64** [comment]
You probably want to open this issue under the relevant fork as the original version does not have provisioning for logos

**Comment by captainjack64** [comment]
@03stevensmi - it's in resources.h file, in hex representation of a png file.

**Comment by 03stevensmi** [comment]
> @03stevensmi - it's in resources.h file, in hex representation of a png file.

Ah thanks mate! Was looking in the wrong file. 
Thanks CJ! ;)
