### ISSUE TITLE
how is hackTV able to generate colorbars by using only one array 

### ISSUE THREAD

**Issue by veso266** [fsphil/hacktv#97]
Hi there, this my seam a stupid question, but I was checking the colorbars generation in [test.c](https://github.com/fsphil/hacktv/blob/master/test.c#L102) and noticied that it seams it is able to generate colorbars by using only one array

Don't you need 3 arrays or one matrix with 3 columns (red,green,blue) to put 3 channels into?

I know its in the code, I just cannot figure out how is this done :smile:

Thanks for anwsering

**Comment by fsphil** [comment]
The RGB values are packed into a single 24-bit* integer: `0xRRGGBB`
Eg. `0xBF0000` is `0xBF` for red, `0x00` for green, `0x00` for blue.

* Technically 32-bit, but the upper 8 bits are not used.
